
import { FoodItem } from '../types';

export const combosItems: FoodItem[] = [
  {
    id: '30',
    name: 'Special Jollof Rice - Turkey',
    description: '2 portions of Special Jollof rice, Turkey with Coldslaw.',
    price: 3500,
    image: '/lovable-uploads/6b41862e-5a24-415a-91b7-3a0d71ee99a8.png',
    category: 'combos',
    tags: ['swallow', 'combo', 'Jollof', 'nigerian'],
    popular: true,
  },
  {
    id: '31',
    name: 'Fried Rice - Chicken Combo',
    description: '2 portions of Fried rice paired with chicken & salad.',
    price: 3000,
    image: '/lovable-uploads/97445272-b727-4b36-987e-3a6dda8f3e1f.png',
    category: 'combos',
    tags: ['rice', 'combo', 'chicken', 'nigerian'],
    popular: false,
  },
  {
    id: '32',
    name: 'Classic Rice Combo',
    description: '3 portions of jollof or fried rice with chicken + any Coca-Cola drink of your choice',
    price: 3500,
    image: '/lovable-uploads/1f82e915-540c-4000-abab-ad15db8ce947.png',
    category: 'combos',
    tags: ['rice', 'jollof', 'combo', 'nigerian'],
    popular: true,
  },
  {
    id: '33',
    name: 'Spaghetti & Chicken',
    description: '3 portions of spaghetti and one piece of chicken (or small turkey) with any Coca-Cola drink of your choice.',
    price: 3450,
    image: '/lovable-uploads/6bcee95d-bcf9-4c29-8791-e5ebc7464e4a.png',
    category: 'combos',
    tags: ['spaghetti', 'chicken', 'combo', 'nigerian'],
    popular: true,
  },
  {
    id: '34',
    name: 'Abula Special',
    description: '3 wraps of amala with ewedu, gbegiri, stew and goat meat + any Coca-Cola drink of your choice',
    price: 3900,
    image: '/lovable-uploads/6da112fa-5856-498e-85e0-a6a4af9ae3bd.png',
    category: 'combos',
    tags: ['amala', 'swallow', 'combo', 'nigerian'],
    popular: false,
  },
  {
    id: '35',
    name: 'Yam Porriage',
    description: '2 Portions of yam porridge (Takeaway Pack included)',
    price: 1000,
    image: '/lovable-uploads/c9794397-e894-401c-ab6c-0f14b8450bf0.png',
    category: 'combos',
    tags: ['yam', 'combo', 'nigerian'],
    popular: false,
  },
  {
    id: '36',
    name: 'Poundo & Egusi With Goat Meat',
    description: '2 wrap of poundo with egusi soup and goat meat.',
    price: 4000,
    image: '/lovable-uploads/5afd5be7-7ba3-4ee3-b948-52d5a7ef92ac.png',
    category: 'combos',
    tags: ['poundo', 'egusi', 'combo', 'nigerian'],
    popular: false,
  },
  {
    id: '37',
    name: 'Ofada Rice with Protein',
    description: '2 full scoops of shaft/stalk with ofada rice and stew served with plantain beef and egg.',
    price: 4500,
    image: '/lovable-uploads/150771b0-7005-4aa8-be5c-feeeff3fde4f.png',
    category: 'combos',
    tags: ['rice', 'ofada', 'combo', 'nigerian'],
    popular: false,
  },
  {
    id: '38',
    name: 'Amala & Abula with Fish',
    description: '2 portion of amala with abula (gbegiri,ewedu with Titus or Kote)',
    price: 3000,
    image: '/lovable-uploads/ec5d1d63-efdb-474b-87fc-9e35b0dc87c7.png',
    category: 'combos',
    tags: ['amala', 'fish', 'combo', 'nigerian'],
    popular: false,
  },
  {
    id: '39',
    name: 'Amala & Abula with Beef & Pomo',
    description: 'Amala and abula served with beef and pomo',
    price: 3500,
    image: '/lovable-uploads/e291a007-ae98-4a23-b40f-bada85c4d212.png',
    category: 'combos',
    tags: ['amala', 'beef', 'pomo', 'combo', 'nigerian'],
    popular: false,
  },
];
