
import { FoodItem } from '../types';

export const proteinItems: FoodItem[] = [
  {
    id: '16',
    name: 'Moi Moi',
    description: 'Steamed bean pudding made from blended beans, peppers, and spices.',
    price: 500,
    image: '/lovable-uploads/moi-moi.jpg',
    category: 'protein',
    tags: ['beans', 'steamed', 'nigerian'],
    popular: false,
  },
  {
    id: '17',
    name: 'Pomo',
    description: 'Nigerian cow skin delicacy, usually served with soup or as a side dish.',
    price: 500,
    image: '/lovable-uploads/pomo.jpg',
    category: 'protein',
    tags: ['meat', 'traditional', 'nigerian'],
    popular: false,
  },
  {
    id: '18',
    name: 'Fried Plantain',
    description: 'Sweet ripe plantain slices fried until golden brown.',
    price: 500,
    image: '/lovable-uploads/plantain.jpg',
    category: 'protein',
    tags: ['plantain', 'fried', 'side dish'],
    popular: false,
  },
  {
    id: '20',
    name: 'Fried Beef',
    description: 'Tender beef chunks marinated and fried with Nigerian spices.',
    price: 500,
    image: '/lovable-uploads/fried_beef.jpg',
    category: 'protein',
    tags: ['beef', 'fried', 'nigerian'],
    popular: false,
  },
  {
    id: '22',
    name: 'Eja Kika',
    description: 'Spicy Nigerian fish recipe with rich peppered sauce and spices.',
    price: 2000,
    image: '/lovable-uploads/ee771644-4c57-42e0-9595-49608802c647.png',
    category: 'protein',
    tags: ['fish', 'spicy', 'nigerian'],
    popular: false,
  },
  {
    id: '21',
    name: 'Chicken Wings',
    description: 'Crispy fried chicken wings with Nigerian seasoning.',
    price: 5000,
    image: '/lovable-uploads/chicken_wing.jpg',
    category: 'protein',
    tags: ['chicken', 'fried', 'appetizer'],
    popular: false,
  },
  {
    id: '23',
    name: 'Goat Meat',
    description: '1 Piece of Goat Meat',
    price: 2000,
    image: '/lovable-uploads/fe36e116-841d-44d7-b6f5-35a6940ef8ad.png',
    category: 'protein',
    tags: ['goat', 'meat', 'nigerian'],
    popular: false,
  },
  {
    id: '24',
    name: 'Turkey (Small)',
    description: '1 piece of small sized fried peppered Turkey',
    price: 3500,
    image: '/lovable-uploads/317b30e9-4634-4936-a9d2-06f599423443.png',
    category: 'protein',
    tags: ['turkey', 'fried', 'nigerian'],
    popular: false,
  },
];

