
import { FoodItem } from '../types';

export const proteinItems: FoodItem[] = [
  {
    id: '16',
    name: 'Moi Moi',
    description: 'Steamed bean pudding made from blended beans, peppers, and spices.',
    price: 500,
    image: '/lovable-uploads/moi-moi.jpg',
    category: 'protein',
    tags: ['beans', 'steamed', 'nigerian'],
    popular: false,
  },
  {
    id: '17',
    name: 'Pomo',
    description: 'Nigerian cow skin delicacy, usually served with soup or as a side dish.',
    price: 500,
    image: '/lovable-uploads/pomo.jpg',
    category: 'protein',
    tags: ['meat', 'traditional', 'nigerian'],
    popular: false,
  },
  {
    id: '18',
    name: 'Fried Plantain',
    description: 'Sweet ripe plantain slices fried until golden brown.',
    price: 500,
    image: '/lovable-uploads/plantain.jpg',
    category: 'protein',
    tags: ['plantain', 'fried', 'side dish'],
    popular: false,
  },
  {
    id: '20',
    name: 'Fried Beef',
    description: 'Tender beef chunks marinated and fried with Nigerian spices.',
    price: 500,
    image: '/lovable-uploads/fried_beef.jpg',
    category: 'protein',
    tags: ['beef', 'fried', 'nigerian'],
    popular: false,
  },
  {
    id: '22',
    name: 'Eja Kika',
    description: 'Spicy Nigerian fish recipe with rich peppered sauce and spices.',
    price: 2000,
    image: '/lovable-uploads/ee771644-4c57-42e0-9595-49608802c647.png',
    category: 'protein',
    tags: ['fish', 'spicy', 'nigerian'],
    popular: false,
  },
];
