
import { FoodItem } from '../types';

export const proteinItems: FoodItem[] = [
  {
    id: '16',
    name: 'Moi Moi',
    description: '1 portion of fried plantain.',
    price: 500,
    image: '/lovable-uploads/7685f6a5-a285-4c99-bf7f-dd6d84283b14.png',
    category: 'protein',
    tags: ['beans', 'steamed', 'nigerian'],
    popular: false,
  },
  {
    id: '17',
    name: 'Pomo',
    description: '1 piece of Ponmo.',
    price: 500,
    image: '/lovable-uploads/a9b19a42-a802-452c-bfbc-e8ce37c44f99.png',
    category: 'protein',
    tags: ['meat', 'traditional', 'nigerian'],
    popular: false,
  },
  {
    id: '18',
    name: 'Fried Plantain',
    description: '1 portion of fried plantain.',
    price: 500,
    image: '/lovable-uploads/1f1bb5f3-bddb-4e0e-8f49-e04c66c39435.png',
    category: 'protein',
    tags: ['plantain', 'fried', 'side dish'],
    popular: false,
  },
  {
    id: '19',
    name: 'Egg',
    description: '1 piece of Egg.',
    price: 350,
    image: '/lovable-uploads/ba60fb10-9e18-4300-b16c-c6191a7b64a2.png',
    category: 'protein',
    tags: ['egg', 'breakfast', 'nigerian'],
    popular: false,
  },
  {
    id: '20',
    name: 'Fried Beef',
    description: 'Tender beef chunks marinated and fried with Nigerian spices.',
    price: 500,
    image: '/lovable-uploads/fried_beef.jpg',
    category: 'protein',
    tags: ['beef', 'fried', 'nigerian'],
    popular: false,
  },
  {
    id: '22',
    name: 'Eja Kika',
    description: 'Spicy Nigerian fish recipe with rich peppered sauce and spices.',
    price: 2000,
    image: '/lovable-uploads/ee771644-4c57-42e0-9595-49608802c647.png',
    category: 'protein',
    tags: ['fish', 'spicy', 'nigerian'],
    popular: false,
  },
  {
    id: '23',
    name: 'Goat Meat',
    description: '1 Piece of Goat Meat',
    price: 2000,
    image: '/lovable-uploads/fe36e116-841d-44d7-b6f5-35a6940ef8ad.png',
    category: 'protein',
    tags: ['goat', 'meat', 'nigerian'],
    popular: false,
  },
  {
    id: '24',
    name: 'Turkey (Small)',
    description: '1 piece of small sized fried peppered Turkey',
    price: 3500,
    image: '/lovable-uploads/317b30e9-4634-4936-a9d2-06f599423443.png',
    category: 'protein',
    tags: ['turkey', 'fried', 'nigerian'],
    popular: false,
  },
];
