
import { FoodItem } from '../types';

export const riceItems: FoodItem[] = [
  {
    id: '1',
    name: 'Jollof Rice',
    description: 'Delicious Nigerian Jollof rice with assorted meat, served with plantain.',
    price: 800,
    image: '/lovable-uploads/8c9c1f0c-346a-417b-bedf-6297d6c798a5.png',
    category: 'rice',
    tags: ['rice', 'spicy', 'nigerian'],
    popular: true,
  },
  {
    id: '15',
    name: 'White Rice',
    description: 'Delicious Nigerian white rice with assorted meat, served with plantain.',
    price: 800,
    image: '/lovable-uploads/0a44627c-3803-4029-9652-1baca80baf6f.jpg',
    category: 'rice',
    tags: ['rice', 'spicy', 'nigerian'],
    popular: true,
  },
  {
    id: '2',
    name: 'Fried Rice',
    description: 'Fragrant rice cooked with coconut milk, served with grilled chicken.',
    price: 800,
    image: '/lovable-uploads/4213cb11-e3f4-483b-9abf-61905e7e1676.png',
    category: 'rice',
    tags: ['rice', 'Fried', 'nigerian'],
    popular: false,
  },
  {
    id: '13',
    name: 'Ofada Rice',
    description: 'Traditional Nigerian brown rice served with spicy Ofada sauce, assorted meat and vegetables.',
    price: 800,
    image: '/lovable-uploads/21b9a6d1-6657-4b30-bfdb-9b8ad81a3bf8.png',
    category: 'rice',
    tags: ['rice', 'traditional', 'nigerian'],
    popular: false,
  },
  {
    id: '19',
    name: 'Spaghetti',
    description: 'Nigerian style spaghetti, cooked with tomato sauce and spices.',
    price: 500,
    image: '/lovable-uploads/spag.jpg',
    category: 'rice',
    tags: ['pasta', 'spicy', 'nigerian'],
    popular: false,
  },
];
