// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yptdwkvgvpqpkwgwirlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGR3a3ZndnBxcGt3Z3dpcmxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODA0ODUsImV4cCI6MjA1ODA1NjQ4NX0.zq8W-EPVfNmB3PQm4jCRL6Nnx9HOVilasexKA_HP8LM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);